DROP TABLE IF EXISTS tags;

CREATE TABLE tags(
    id SERIAL PRIMARY KEY,
    comment VARCHAR(255) NOT NULL,
    username VARCHAR(300) NOT NULL,
    postId INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tags
	ADD FOREIGN KEY (postId)
	REFERENCES images(Id)
	ON DELETE CASCADE;
